// quick-starts/vue-quick-start/src/components/SendTransaction.vue
<script setup lang="ts">
import { parseEther } from 'viem';
import { useSendTransaction, useWaitForTransactionReceipt } from '@wagmi/vue';

const { data: hash, error, isPending, sendTransaction } = useSendTransaction();

function submit(event: Event) {
  const formData = new FormData(event.target as HTMLFormElement);
  const to = formData.get('address') as `0x${string}`;
  const value = formData.get('value') as string;
  sendTransaction({ to, value: parseEther(value) });
}

const { isLoading: isConfirming, isSuccess: isConfirmed } =
  useWaitForTransactionReceipt({
    hash,
  });
</script>

<template>
  <div class="container">
    <div className="stack">
      <form class="set" @submit.prevent="submit">
        <input name="address" placeholder="Address" required />
        <input
          name="value"
          placeholder="Amount (ETH)"
          type="number"
          step="0.000000001"
          required
        />
        <button type="submit" :disabled="isPending">Send</button>
      </form>
      <div v-if="hash">Transaction Hash: {{ hash }}</div>
      <div v-if="isConfirming">Waiting for confirmation...</div>
      <div v-if="isConfirmed">Transaction confirmed.</div>
      <div v-if="error">
        Error: {{ (error as BaseError).shortMessage || error.message }}
      </div>
    </div>
  </div>
</template>

// custom-authentication/grouped-connection/modal-google-email-passwordless-grouped-example/src/components/sendTransaction.tsx
import { FormEvent } from "react";
import { useWaitForTransactionReceipt, useSendTransaction, BaseError } from "wagmi";
import { Hex, parseEther } from "viem";

export function SendTransaction() {
  const { data: hash, error, isPending, sendTransaction } = useSendTransaction()

  async function submit(e: FormEvent<HTMLFormElement>) {
    e.preventDefault()
    const formData = new FormData(e.target as HTMLFormElement)
    const to = formData.get('address') as Hex
    const value = formData.get('value') as string
    sendTransaction({ to, value: parseEther(value) })
  }

  const { isLoading: isConfirming, isSuccess: isConfirmed } =
    useWaitForTransactionReceipt({
      hash,
    })

  return (
    <div>
      <h2>Send Transaction</h2>
      <form onSubmit={submit}>
        <input name="address" placeholder="Address" required />
        <input
          name="value"
          placeholder="Amount (ETH)"
          type="number"
          step="0.000000001"
          required
        />
        <button disabled={isPending} type="submit">
          {isPending ? 'Confirming...' : 'Send'}
        </button>
      </form>
      {hash && <div>Transaction Hash: {hash}</div>}
      {isConfirming && 'Waiting for confirmation...'}
      {isConfirmed && 'Transaction confirmed.'}
      {error && (
        <div>Error: {(error as BaseError).shortMessage || error.message}</div>
      )}
    </div>
  )
}
