// web-modal-sdk/quick-starts/react-modal-solana-quick-start/src/components/switchNetwork.tsx
import { useSwitchChain, useWeb3Auth } from '@web3auth/modal/react'

export function SwitchChain() {
  const { web3Auth } = useWeb3Auth();

  const { switchChain, error } = useSwitchChain()

  return (
    <div>
      <h2>Switch Chain</h2>
      <h3>Connected to {web3Auth?.currentChain?.displayName}</h3>
      {web3Auth?.coreOptions.chains?.map((chain) => {
        if (chain.chainId === "0x67" || chain.chainId === "0x66" || chain.chainId === "0x65") {
          return (
            <button
              disabled={web3Auth?.currentChain?.chainId === chain.chainId}
              key={chain.chainId}
              onClick={() => switchChain(chain.chainId)}
              type="button"
              className="card"
            >
              {chain.displayName}
            </button>
          )
        }
      })}

      {error?.message}
    </div>
  )
}

// web-modal-sdk/quick-starts/vue-modal-solana-quick-start/src/components/switchNetwork.vue
<script setup lang="ts">
import { useWeb3Auth, useSwitchChain } from '@web3auth/modal/vue';
import { computed } from 'vue';

const { web3Auth } = useWeb3Auth();
const { switchChain, error } = useSwitchChain();

const filteredChains = computed(() => {
  const chains = web3Auth.value?.coreOptions?.chains || [];
  return chains.filter(
    (chain: any) => chain.chainId === '0x67' || chain.chainId === '0x66' || chain.chainId === '0x65'
  );
});


const currentChainName = computed(() => web3Auth.value?.currentChain?.displayName || '');
</script>

<template>
  <div>
    <h2>Switch Chain</h2>
    <h3>Connected to {{ currentChainName }}</h3>
    <button
      v-for="chain in filteredChains"
      :key="chain.chainId"
      :disabled="web3Auth?.currentChain?.chainId === chain.chainId"
      @click="switchChain({ chainId: chain.chainId })"
      type="button"
      class="card"
    >
      {{ chain.displayName }}
    </button>
    <div v-if="error" class="error">{{ error.message }}</div>
  </div>
</template>
