// web-no-modal-sdk/quick-starts/react-no-modal-solana-quick-start/src/components/getBalance.tsx
import { useSolanaWallet } from "@web3auth/no-modal/react/solana";
import {
  LAMPORTS_PER_SOL,
  PublicKey,
} from "@solana/web3.js";
import { useEffect, useState } from "react";

export function Balance() {
  const { accounts, connection } = useSolanaWallet();
  const [balance, setBalance] = useState<number | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const fetchBalance = async () => {
    if (connection && accounts && accounts.length > 0) {
      try {
        setIsLoading(true);
        setError(null);
        const publicKey = new PublicKey(accounts[0]);
        const balance = await connection.getBalance(publicKey);
        setBalance(balance);
      } catch (err) {
        setError(err instanceof Error ? err.message : "Unknown error");
      } finally {
        setIsLoading(false);
      }
    }
  };

  useEffect(() => {
    fetchBalance();
  }, [connection, accounts]);

  return (
    <div>
      <h2>Balance</h2>
      <div>
        {balance !== null && `${balance / LAMPORTS_PER_SOL} SOL`} 
      </div>
        {isLoading && <span className="loading">Loading...</span>}
        {error && <span className="error">Error: {error}</span>}
      <button onClick={fetchBalance} type="submit" className="card">
          Fetch Balance
      </button>
    </div>
  )
}

// quick-starts/vue-solana-quick-start/src/components/getBalance.vue
<script setup lang="ts">
import { ref, onMounted, watch } from 'vue';
import { useSolanaWallet } from "@web3auth/modal/vue/solana";
import { useWeb3Auth } from "@web3auth/modal/vue";
import { LAMPORTS_PER_SOL, PublicKey } from "@solana/web3.js";

const { web3Auth } = useWeb3Auth();
const { accounts, connection } = useSolanaWallet();
const balance = ref<number | null>(null);
const isLoading = ref(false);
const error = ref<string | null>(null);

const fetchBalance = async () => {
  if (!web3Auth.value?.connected) {
    error.value = "Please connect your wallet first";
    return;
  }
    try {
      isLoading.value = true;
      error.value = null;
      // Check if accounts exist and have values before creating PublicKey
      if (!accounts.value || accounts.value.length === 0) {
        console.error("No accounts found. Please connect your wallet.", accounts.value);
        throw new Error("No accounts found. Please connect your wallet.");
      }
      const publicKey = new PublicKey(accounts.value[0]);
      const balanceResult = await connection.value!.getBalance(publicKey);
      balance.value = balanceResult;
    } catch (err) {
      console.error("Error fetching balance:", err);
      error.value = err instanceof Error ? err.message : "Unknown error";
      balance.value = null;
    } finally {
      isLoading.value = false;
    }
};

// Fetch balance when connection or accounts change
watch([connection, accounts], () => {
  if (web3Auth.value?.connected) {
    fetchBalance();
  }
});

// Initial fetch on component mount
onMounted(() => {
  if (web3Auth.value?.connected) {
    fetchBalance();
  }
});
</script>

<template>
  <div>
    <h2>Balance</h2>
    <div v-if="balance !== null">
      <span>{{ balance / LAMPORTS_PER_SOL }} SOL</span>
    </div>
    <div v-if="isLoading" class="loading">Loading...</div>
    <div v-if="error" class="error">Error: {{ error }}</div>
    <button @click="fetchBalance" type="button" class="card" :disabled="isLoading">
      Fetch Balance
    </button>
  </div>
</template>
