// web-no-modal-sdk/quick-starts/vue-no-modal-quick-start/src/components/SwitchNetwork.vue
<script setup lang="ts">
import { useChainId, useSwitchChain } from '@wagmi/vue';

const chainId = useChainId();
const { chains, error, switchChain } = useSwitchChain();
</script>

<template>
  <div class="container">
    <div class="stack">
      <h2>Switch Chain</h2>
      <h3 class="text">Connected to {{ chainId }}</h3>
      <div class="set">
        <button
          v-for="chain in chains"
          :key="chain.id"
          :disabled="chainId === chain.id"
          @click="switchChain({ chainId: chain.id })"
          type="button"
          class="card"
        >
          {{ chain.name }}
        </button>
      </div>
      <div v-if="error" class="error">{{ error.message }}</div>
    </div>
  </div>
</template>

// web-no-modal-sdk/wagmi/wagmi-no-modal-example-email/src/switchNetwork.tsx
import { useChainId, useSwitchChain } from 'wagmi'

export function SwitchChain() {
  const chainId = useChainId()
  const { chains, switchChain, error } = useSwitchChain()

  return (
    <div>
      <h2>Switch Chain</h2>
      <h3>Connected to {chainId}</h3>
      {chains.map((chain) => (
        <button
          disabled={chainId === chain.id}
          key={chain.id}
          onClick={() => switchChain({ chainId: chain.id })}
          type="button"
        >
          {chain.name}
        </button>
      ))}

      {error?.message}
    </div>
  )
}
